---
# This role manages groups on the client
- name: gather data
  set_fact:
    data: "{{ hostvars['localhost'].profile_json['Groups'] }}"
    
- name: managing the groups
  group:
      name: "{{ item.Name }}"
      state: "{{ item.State }}"
  with_items: "{{ data }}"
  become: yes
  become_user: root
  become_method: sudo
