# Ansible role to add apt_keys
---
- name: gather data
  set_fact:
    data: "{{ hostvars['localhost'].profile_json['Apt_Keys'] }}"

- name: add "{{ item.Name }}"
  apt_key:
    url: "{{ item.URL }}"
    state: present
  with_items: "{{ data }}"
  become: yes
  become_user: root
  become_method: sudo
