---
IMAGE:
  CLOUD_IMAGE_URL: "$CLOUD_IMAGE_URL"
  CLOUD_INIT_TEMPLATE: "$CLOUD_INIT_TEMPLATE"
  ISO_FILE: "$ISO_FILE"
VM:
  VM_NAME: "$VM_NAME"
  VM_USER: "$VM_USER"
  GITHUB_USER: "$GITHUB_USER"
  USER: "$USER"
  DISK_NAME: "$DISK_NAME"
  DISK_SIZE: "$DISK_SIZE"
  MEMORY: "$MEMORY"
  SOCKETS: "$SOCKETS"
  PHYSICAL_CORES: "$PHYSICAL_CORES"
  THREADS: "$THREADS"
  VM_KEY: "$VM_KEY"
  VM_KEY_FILE: "$VM_KEY_FILE"
  UUID: "$UUID"
  MAC_ADDR: "$MAC_ADDR"
  PASSWD: "$PASSWD"
GPU:
  GPU_ACCEL: "$GPU_ACCEL"
  GPU_VENDOR: "$GPU_VENDOR"
  GPU_PCI_ID: "$GPU_PCI_ID"
NETWORK:
  HOST:
    HOST_ADDRESS: "$HOST_ADDRESS"
    DNS_SERVER: "$DNS_SERVER"
    IP_GATEWAY: "$IP_GATEWAY"
    HOST_SSH_PORT: "$HOST_SSH_PORT"
    HOST_INTERFACE: "$HOST_INTERFACE"
    BRIDGE_NAME: "$BRIDGE_NAME"
  GUEST:
    STATIC_IP: "$STATIC_IP"
    STATIC_IP_ADDRESS: "$STATIC_IP_ADDRESS"
    VM_SSH_PORT: "$VM_SSH_PORT"
    VNC_PORT: "$VNC_PORT"
    TAP_DEVICE_NUMBER: "$TAP_DEVICE_NUMBER"
    NETWORK_NUMBER: "$NETWORK_NUMBER"
    INTERFACE: "$INTERFACE"
