- hosts: localhost
  become: yes

  vars:
    job_list_json: "{{ lookup('file', 'cron-jobs.json') | from_json }}"

  pre_tasks:
  - name: Setting package list as a fact
    set_fact: job_list="{{ job_list_json }}"

  roles:
   - role: cron