---
# A role to download files to the remote client
- name: download section
  set_fact:
    data: "{{ hostvars['localhost'].profile_json['Downloads'] }}"

- name: displaying download urls from config file
  debug:
    msg: "URL: {{ item.URL }}, dest: {{ item.Destination }}"
  with_items: "{{ data }}"

- name: downloading items from the internet
  get_url:
    url: "{{ item.URL }}"
    dest: "{{ item.Destination }}"
  with_items: "{{ data }}"
